import type { Request, Response } from "express";
import { RecurringTransaction } from "./recurring-transactions.model.ts";
import { Category } from "../category/category.model.ts";
import { Transaction } from "../transactions/transaction.model.ts";
import { processRecurringTransactions } from "../../helper/recurring-processor/recurringProcessor.ts";
import {
  validateCreateRecurringTransaction,
  validateUpdateRecurringTransaction,
} from "./recurring-transactions.validation.ts";
import ResponseBuilder from "../../helper/responce-builder/responseBuilder.ts";

// Helper: compute next due date based on frequency
function computeNextDueDate(fromDate: string, frequency: string): string {
  const d = new Date(fromDate);
  switch (frequency) {
    case "Daily":
      d.setDate(d.getDate() + 1);
      break;
    case "Weekly":
      d.setDate(d.getDate() + 7);
      break;
    case "Monthly":
      d.setMonth(d.getMonth() + 1);
      break;
    case "Yearly":
      d.setFullYear(d.getFullYear() + 1);
      break;
  }
  return d.toISOString().split("T")[0];
}

// Create
export const createRecurringTransaction = async (
  req: Request,
  res: Response
): Promise<Response | void> => {
  const { error, validatedData } = validateCreateRecurringTransaction(req.body);
  if (error) {
    return ResponseBuilder.error(res, 400, "Validation error", error.details[0].message);
  }

  const userId = req.user?.id;
  if (!userId) return ResponseBuilder.error(res, 401, "User is not authenticated");

  try {
    const recurring = await RecurringTransaction.create({
      userId,
      amount: validatedData!.amount,
      type: validatedData!.type,
      categoryId: validatedData!.categoryId,
      paymentMethod: validatedData!.paymentMethod || "Cash",
      frequency: validatedData!.frequency,
      startDate: validatedData!.startDate,
      nextDueDate: validatedData!.startDate,
      notes: validatedData!.notes || null,
      isActive: 1,
      deleted: 0,
    });

    await recurring.reload({
      include: [{ model: Category, attributes: ["id", "name"] }],
    });

    return ResponseBuilder.success(res, 201, "Recurring transaction created successfully", { recurring });
  } catch (err: any) {
    return ResponseBuilder.error(res, 500, "Server error", err.message || String(err));
  }
};

// Get All
export const getRecurringTransactions = async (
  req: Request,
  res: Response
): Promise<Response | void> => {
  const userId = req.user?.id;
  if (!userId) return ResponseBuilder.error(res, 401, "User is not authenticated");

  try {
    const items = await RecurringTransaction.findAll({
      where: { userId, deleted: 0 },
      include: [{ model: Category, attributes: ["id", "name"] }],
      order: [["createdAt", "DESC"]],
    });
    return ResponseBuilder.success(res, 200, "Recurring transactions retrieved", { result: items });
  } catch (err: any) {
    return ResponseBuilder.error(res, 500, "Server error", err.message || String(err));
  }
};

// Update
export const updateRecurringTransaction = async (
  req: Request,
  res: Response
): Promise<Response | void> => {
  const id = Number(req.params.id);
  if (isNaN(id)) return ResponseBuilder.error(res, 400, "Invalid ID");

  const { error, validatedData } = validateUpdateRecurringTransaction(req.body);
  if (error) return ResponseBuilder.error(res, 400, "Validation error", error.details[0].message);

  const userId = req.user?.id;
  if (!userId) return ResponseBuilder.error(res, 401, "User is not authenticated");

  try {
    const item = await RecurringTransaction.findOne({ where: { id, userId, deleted: 0 } });
    if (!item) return ResponseBuilder.error(res, 404, "Recurring transaction not found");

    // 1. Delete all transactions generated by this recurring transaction
    await Transaction.destroy({ where: { recurringTransactionId: item.id } });

    const newFrequency = validatedData!.frequency ?? item.frequency;
    const newStartDate = validatedData!.startDate ?? item.startDate;

    // 2. Update recurring properties and reset nextDueDate to newStartDate to regenerate from the beginning
    await item.update({
      amount: validatedData!.amount ?? item.amount,
      type: validatedData!.type ?? item.type,
      categoryId: validatedData!.categoryId ?? item.categoryId,
      paymentMethod: validatedData!.paymentMethod !== undefined ? validatedData!.paymentMethod : item.paymentMethod,
      frequency: newFrequency,
      startDate: newStartDate,
      nextDueDate: newStartDate,
      notes: validatedData!.notes !== undefined ? validatedData!.notes : item.notes,
    });

    // 3. Re-run processor to catch up and generate transactions under the new configuration
    await processRecurringTransactions();

    await item.reload({
      include: [{ model: Category, attributes: ["id", "name"] }],
    });

    return ResponseBuilder.success(res, 200, "Updated successfully", { item });
  } catch (err: any) {
    return ResponseBuilder.error(res, 500, "Server error", err.message || String(err));
  }
};

// Toggle Active/Pause
export const toggleRecurringTransaction = async (
  req: Request,
  res: Response
): Promise<Response | void> => {
  const id = Number(req.params.id);
  if (isNaN(id)) return ResponseBuilder.error(res, 400, "Invalid ID");

  const userId = req.user?.id;
  if (!userId) return ResponseBuilder.error(res, 401, "User is not authenticated");

  try {
    const item = await RecurringTransaction.findOne({ where: { id, userId, deleted: 0 } });
    if (!item) return ResponseBuilder.error(res, 404, "Recurring transaction not found");

    await item.update({ isActive: item.isActive === 1 ? 0 : 1 });
    return ResponseBuilder.success(res, 200, `Recurring transaction ${item.isActive === 1 ? "paused" : "resumed"}`);
  } catch (err: any) {
    return ResponseBuilder.error(res, 500, "Server error", err.message || String(err));
  }
};

// Delete
export const deleteRecurringTransaction = async (
  req: Request,
  res: Response
): Promise<Response | void> => {
  const id = Number(req.params.id);
  if (isNaN(id)) return ResponseBuilder.error(res, 400, "Invalid ID");

  const userId = req.user?.id;
  if (!userId) return ResponseBuilder.error(res, 401, "User is not authenticated");

  try {
    const item = await RecurringTransaction.findOne({ where: { id, userId, deleted: 0 } });
    if (!item) return ResponseBuilder.error(res, 404, "Recurring transaction not found");

    await item.update({ deleted: 1, deletedAt: new Date() });
    
    // Soft-delete all associated transactions created by this recurring template
    await Transaction.update(
      { deleted: 1, deletedAt: new Date() },
      { where: { recurringTransactionId: item.id } }
    );

    return ResponseBuilder.success(res, 200, "Recurring transaction deleted successfully");
  } catch (err: any) {
    return ResponseBuilder.error(res, 500, "Server error", err.message || String(err));
  }
};
